src/Entity/Dossier.php
<?php

namespace App\Entity;

use App\Repository\DossierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DossierRepository")
 * @ORM\Table(name="dossier", indexes={@ORM\Index(columns={"titre", "analyse"}, flags={"fulltext"})})
 * @UniqueEntity(fields={"cote"}, errorPath="titre", message="doss.cote_unique")
 */
class Dossier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cote;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $analyse;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_butoire;

    /**
     * Bidirectional - One-To-Many (INVERSED SIDE)
     * One Dossier can have many documents, which use it
     * @var ArrayCollection $document
     * @ORM\OneToMany(targetEntity=Document::class, mappedBy="dossier", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $document ;

    /**
     * iniitilized createdAt field dateTime to Now
     */
    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->document = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCote(): ?string
    {
        return $this->cote;
    }

    public function setCote(string $cote): self
    {
        $this->cote = $cote;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAnalyse(): ?string
    {
        return $this->analyse;
    }

    public function setAnalyse(?string $analyse): self
    {
        $this->analyse = $analyse;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateButoire(): ?\DateTimeInterface
    {
        return $this->date_butoire;
    }

    public function setDateButoire(?\DateTimeInterface $date_butoire): self
    {
        $this->date_butoire = $date_butoire;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocument(): Collection
    {
        return $this->document;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->document->contains($document)) {
            $this->document[] = $document;
            $document->setDossier($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->document->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getDossier() === $this) {
                $document->setDossier(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->cote;
    }
}

src/Form/DossierType.php
<?php

namespace App\Form;

use App\Entity\Dossier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DossierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('cote', TextType::class, [
                'label' => 'Code dossier'
            ])
            ->add('titre')
            ->add('analyse')
            ->add('date_debut')
            ->add('date_butoire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Dossier::class,
        ]);
    }
}

src/Controller/DossierController.php
<?php

namespace App\Controller;

use App\Entity\Dossier;
use App\Form\Dossier1Type;
use App\Form\SearchDossierType;
use App\Repository\DossierRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/dossier")
 */
class DossierController extends AbstractController
{
    /**
     * @Route("/", name="dossier_index", methods={"GET", "POST"})
     */
    public function index(DossierRepository $dossierRepository, Request $request): Response
    {

        #$dossier = $dossierRepository->findBy(['active' => true], ['created_at' => "desc"], 10);
        $dossier = $dossierRepository->findAll();

        $form = $this->createForm(SearchDossierType::class);

        $search = $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            # code... recherche les dossiers correspondant aux mots clés
            $dossier = $dossierRepository->search($search->get('mots')->getData());
        }

        return $this->render('dossier/index.html.twig', [
            'dossiers' => $dossier,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/new", name="dossier_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $dossier = new Dossier();
        $form = $this->createForm(Dossier1Type::class, $dossier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($dossier);
            $entityManager->flush();

            return $this->redirectToRoute('dossier_index');
        }

        return $this->render('dossier/new.html.twig', [
            'dossier' => $dossier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dossier_show", methods={"GET"})
     */
    public function show(Dossier $dossier): Response
    {
        return $this->render('dossier/show.html.twig', [
            'dossier' => $dossier,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="dossier_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Dossier $dossier): Response
    {
        $form = $this->createForm(Dossier1Type::class, $dossier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dossier_index');
        }

        return $this->render('dossier/edit.html.twig', [
            'dossier' => $dossier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dossier_delete", methods={"POST"})
     */
    public function delete(Request $request, Dossier $dossier): Response
    {
        if ($this->isCsrfTokenValid('delete'.$dossier->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($dossier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('dossier_index');
    }

    /**
     * Search action method for Live earch feature.
     * Creates a new ActionItem entity
     * 
     * @Route("/search", name="doss_search")
     */
    public function searchAction(DossierRepository $dr,  Request $request): Response
    {
        //$dossier = $dr->findAll();

        $query = $request->query->get('searchField', ''); // on recupere le input $_GET
        $limit = $request->query->get('l', 10);

        if (!$request->isXmlHttpRequest()) {
            return $this->render('dossier/search.html.twig', ['query' => $query]);
        }

        // $foundDossiers = $dr->search($request->get('searchField')->getData());
        $foundDossiers = $dr->findBySearchQuery($request, $limit);

        //$foundDossiers = $dr->search($query);

        $results = [];

        foreach ($foundDossiers as $dossier) {
            $results[] = [
                'cote' => htmlspecialchars($dossier->getCote(), \ENT_COMPAT | \ENT_HTML5),
                'titre' => htmlspecialchars($dossier->getTitre(), \ENT_COMPAT | \ENT_HTML5),
                'analyse' => htmlspecialchars($dossier->getAnalyse(), \ENT_COMPAT | \ENT_HTML5),
                'date_debut' => $dossier->getDateDebut()->format('M d, Y'),
                'date_butoire' => $dossier->getDateButoire()->format('M d, Y'),
            ];
        }

        return $this->json($results);
    } 

}

templates/dossier/_delete_form.html.twig
<form method="post" action="{{ path('dossier_delete', {'id': dossier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ dossier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/dossier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Dossier{% endblock %}

{% block body %}
    <h1>Edit Dossier</h1>

    {{ include('dossier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('dossier_index') }}">back to list</a>

    {{ include('dossier/_delete_form.html.twig') }}
{% endblock %}

templates/dossier/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Liste Dossier{% endblock %}

{% block body %}

    <div class="form-inline input-group" style="margin-left: 70%;">
            {{ form_start(form) }}
                {{ form_widget(form) }}
            {{ form_end(form) }}
    </div>
        <div class="form-outline">
        </div>

    <h1>Liste des Dossiers /Classeurs</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Cote</th>
                <th>Titre</th>
                <th>Analyse</th>
                <th>Date_debut</th>
                <th>Date_butoire</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dossier in dossiers %}
            <tr>
                <td>{{ dossier.cote }}</td>
                <td>{{ dossier.titre }}</td>
                <td>{{ dossier.analyse }}</td>
                <td>{{ dossier.dateDebut ? dossier.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ dossier.dateButoire ? dossier.dateButoire|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('dossier_show', {'id': dossier.id}) }}"><i class="fa fa-eye" aria-hidden="true"> ouvrir</i></a>
                    {#<a href="{{ path('dossier_edit', {'id': dossier.id}) }}">edit</a> on cache aux anonymous cette partie #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('dossier_new') }}" class="btn btn-primary">Nouveau dossier</a>
{% endblock %}

templates/dossier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Dossier{% endblock %}

{% block body %}
    <h1>Nouveau Dossier</h1>

    {{ include('dossier/_form.html.twig') }}

    <a href="{{ path('dossier_index') }}">back to list</a>
{% endblock %}

templates/dossier/search.ajax.twig
{% if results is defined and results is iterable and results|length >= 1 %}
    {% for result in results %}
        <p style="display:inline-block;width:200px;">{{ result.cote }}</p>
        <p style="display:inline-block;width:100px;">{{ result.titre }}</p>
        <p style="display:inline-block;width:300px;">{{ result.analyse }}</p>
        <p style="display:inline-block;width:120px;">{{ result.date_debut }}</p>
        <p style="display:inline-block;width:120px;">{{ result.date_butoire }}</p>
    {% endfor %}
{% endif %}

templates/dossier/search.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {# 
     #}
    {{ encore_entry_script_tags('search') }}

    {# Jquery is necessary#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>

        (function ($) {
            'use strict';


            // INSTANTS SEARCH PUBLIC CLASS DEFINITION
            // =======================================

            var InstantSearch = function (element, options) {
                this.$input = $(element);
                this.$form = this.$input.closest('form');
                this.$preview = $('<ul class="search-preview list-group">').appendTo(this.$form);
                this.options = $.extend({}, InstantSearch.DEFAULTS, this.$input.data(), options);

                this.$input.keyup(this.debounce());
            };

            InstantSearch.DEFAULTS = {
                minQueryLength: 2,
                limit: 10,
                delay: 500,
                noResultsMessage: 'No results found'
            };

            InstantSearch.prototype.debounce = function () {
                var delay = this.options.delay;
                var search = this.search;
                var timer = null;
                var self = this;

                return function () {
                    clearTimeout(timer);
                    timer = setTimeout(function () {
                        search.apply(self);
                    }, delay);
                };
            };

            InstantSearch.prototype.search = function () {
                var query = $.trim(this.$input.val()).replace(/\s{2,}/g, ' ');
                if (query.length < this.options.minQueryLength) {
                    this.$preview.empty();
                    return;
                }

                var self = this;
                var data = this.$form.serializeArray();
                data['l'] = this.limit;

                $.getJSON(this.$form.attr('action'), data, function (items) {
                    self.show(items);
                });
            };

            InstantSearch.prototype.show = function (items) {
                var $preview = this.$preview;
                var itemTemplate = this.options.itemTemplate;

                if (0 === items.length) {
                    $preview.html(this.options.noResultsMessage);
                } else {
                    $preview.empty();
                    $.each(items, function (index, item) {
                        $preview.append(itemTemplate.render(item));
                    });
                }
            };

            // INSTANTS SEARCH PLUGIN DEFINITION
            // =================================

            function Plugin(option) {
                return this.each(function () {
                    var $this = $(this);
                    var instance = $this.data('instantSearch');
                    var options = typeof option === 'object' && option;

                    if (!instance) $this.data('instantSearch', (instance = new InstantSearch(this, options)));

                    if (option === 'search') instance.search();
                })
            }

            $.fn.instantSearch = Plugin;
            $.fn.instantSearch.Constructor = InstantSearch;

        })(window.jQuery);


        $(function() {
            $('.search-field')
                .instantSearch({
                    delay: 100,
                })
                .keyup();
        });

    </script>
{% endblock %}

{% block main %}

    <form action="{{ path('doss_search') }}" method="get">
        <div class="form-group">
            <input name="q"
                   class="form-control search-field"
                   placeholder="{{ 'post.search_for'|trans }}"
                   autocomplete="off"
                   value="{{ query }}"
                   autofocus
                   data-no-results-message="{{ 'post.search_no_results'|trans }}"
            >
        </div>
    </form>

    <div id="results">
    </div>

{% endblock %}

{# {% block sidebar %}
    {{ parent() }}

    {{ show_source_code(_self) }}
{% endblock %} #}

templates/dossier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dossier{% endblock %}

{% block body %}
    <h1>Dossier</h1>

    <table class="table">
        <tbody>
            
            <tr>
                <th>Cote</th>
                <td>{{ dossier.cote }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ dossier.titre }}</td>
            </tr>
            <tr>
                <th>Analyse</th>
                <td>{{ dossier.analyse }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ dossier.dateDebut ? dossier.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_butoire</th>
                <td>{{ dossier.dateButoire ? dossier.dateButoire|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('dossier_index') }}">back to list</a>

    <a href="{{ path('dossier_edit', {'id': dossier.id}) }}">edit</a>

    {{ include('dossier/_delete_form.html.twig') }}
{% endblock %}